# A configuration file for our Quality Infrastructure builds: https://wiki.gpii.net/w/Quality_Infrastructure
email: tony@raisingthefloor.org
env_runtime: linux-desktop

apps:
  - app_name: gpii-handlebars
    git_repository: https://github.com/the-t-in-rtf/gpii-handlebars.git
    git_branch: GPII-1810
    software_stack: nodejs
    software_stack_version: lts
    folder:
      dest: /app/gpii-handlebars
    run_in: fedora
    deploy: false
    setup:
      - sudo yum install -y chromedriver
      - yarn install
    test_cmds:
      - BROWSERS=chrome yarn test
